### ISSUE TITLE
When identity is specified a redundant slash character is added in the end

### ISSUE THREAD

**Issue by xtrmstep** [BulletTrainHQ/bullet-train-dotnet-client#10]
Hi,

I've noticed that if I use identity, then a user is added with incorrect id, such as `user_id/`. It's because of `AppendPath` in the class `UrlExtension`.
There are two consequences from this:

1. the user has additional slash which wasn't specified in the client application
2. BulletTrain Web doesn't correctly show user with additional slash.

At the same time this is not crucial issue. It is still possible to use Web and Api with this identity.

Regards,

**Comment by dabeeeenster** [comment]
Hi - Can you confirm the version of the library?

**Comment by xtrmstep** [comment]
@dabeeeenster  I'm using 2.1.1
