### ISSUE TITLE
using .NET client SDK always return "Value cannot be null. Parameter name: value" error

### ISSUE THREAD

**Issue by malah-code** [BulletTrainHQ/bullet-train-dotnet-client#6]
When we use .NET client SDK always return "**Value cannot be null. Parameter name: value**" error. 

When we call .net  code like below

            BulletTrainConfiguration configuration = new BulletTrainConfiguration()
            {
                ApiUrl = "https://features.xyz.ca/api/v1/",
                EnvironmentKey = EnvironmentKey
            };

            BulletTrainClient bulletClient = new BulletTrainClient(configuration);
            bool featureEnabled = await BulletTrainClient.instance.HasFeatureFlag("configuration_resource");
            string result = "";
            if (featureEnabled)
            {
                result = " run the code to execute enabled feature";
            }
            else
            {
                result = "run the code if feature switched off";
            } 
            return "value - " + result;

Generate Exception 

    <Message>An error has occurred.</Message>
    <ExceptionMessage>Value cannot be null. Parameter name: value</ExceptionMessage>
    <ExceptionType>System.ArgumentNullException</ExceptionType>
 
After some investigation about the inner HTTP call to the API, we found that the root cause is that :

 
    GET https://features.xyz.ca/api/v1/flags/ HTTP/1.1
    X-Environment-Key: xyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxy
    Host: features.xyz.ca
    Connection: Keep-Alive
      
 

This returns : 

     HTTP/1.1 403 Forbidden
     Server: awselb/2.0
    Date: Thu, 17 Sep 2020 14:26:42 GMT
    Content-Type: text/html
    Content-Length: 134
    Connection: keep-alive
    
    <html>
    <head><title>403 Forbidden</title></head>
    <body bgcolor="white">
    <center><h1>403 Forbidden</h1></center>
    </body>
    </html>
        

 
After some investigation and compare between .NET SDK and Direct API Access by curl , we found  that the direct call to curl is working with same parameters

`
curl https://features.xyz.ca/api/v1/flags/ -H "X-Environment-Key: xyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxy"
`

This return all features in JSON.

So, why .NET SDK not working, any Idea?

**Comment by dabeeeenster** [comment]
Thanks for the bug report - we'll take a look!

**Comment by dabeeeenster** [comment]
@malah-code are you able to reproduce this against the official hosted API?

**Comment by malah-code** [comment]
@dabeeeenster  , Thanks for fast reply. I tested it with https://api.bullet-train.io/api/v1/ and it works. so are there any configs I miss in my own server setup?

**Comment by dabeeeenster** [comment]
its hard to say without knowing exactly what your setup looks like. What version of the API are you running?

**Comment by malah-code** [comment]
Not sure where could I get the version

**Comment by dabeeeenster** [comment]
Will make a point of adding version info to the API. Can you describe how you are running the API? Docker etc?

**Comment by malah-code** [comment]
AWS Container.
Also I noticed that for the same request if I add `User-Agent: sdfsdf` , it work fine, but without User-Agent  return `403 Forbidden`

 GET https://features.xyz.ca/api/v1/flags/ HTTP/1.1
 X-Environment-Key: xyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxy
 User-Agent: sdfsdf
 Host: features.freedommobile.ca

**Comment by dabeeeenster** [comment]
I'm not able to reproduce this Im afraid. Are you able to provide the exact two curl commands; 1 that fails and 1 that works?

**Comment by malah-code** [comment]
Here are both requests
![image](https://user-images.githubusercontent.com/96269/93624660-af5db080-f9ae-11ea-81fc-934f99c43612.png)
![image](https://user-images.githubusercontent.com/96269/93624714-c4d2da80-f9ae-11ea-8bbb-d7e0b872d172.png)

**Comment by dabeeeenster** [comment]
It looks like that 403 response is coming directly from the AWS ELB and not the Bullet Train app server. We do offer enterprise support packages for self hosted deployments if that is of interest?

**Comment by andrewshawcare** [comment]
We figured it out. There's a rule entitled, `NoUserAgent_HEADER` in the `AWSManagedCommonRuleSet` core rule set for AWS web application firewall (WAF): https://docs.aws.amazon.com/waf/latest/developerguide/aws-managed-rule-groups-list.html#aws-managed-rule-groups-baseline

We have excluded the rule for now to allow for Bullet Train traffic, but ideally Bullet Train would use a `User-Agent` header to ensure we can prevent malicious web requests.

**Comment by dabeeeenster** [comment]
Ah understood - that makes sense. I'll add a ticket to have SDK clients send user agents.
